# Generated by Django 5.2.6 on 2026-03-20 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RunHistory',
        ),
    ]
